[disambiguate]
model = "${DISAMBIGUATOR}"
base_url = "${DISAMBIGUATOR_URL}"

[route]
model = "${ROUTER}"
base_url = "${ROUTER_URL}"

[searchify]
model = "${SEARCHIFIER}"
base_url = "${SEARCHIFIER_URL}"

[rerank]
model = "${RERANKER}"
base_url = "${RERANKER_URL}"

[summarize]
model = "${SUMMARIZER}"
base_url = "${SUMMARIZER_URL}"

[default]
model = "${MODEL}"
base_url = "${MODEL_URL}"