[project]
name = "orca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.12"
dependencies = [
    "langchain-chroma>=0.2,<0.3",
    "langchain-community>=0.3,<0.4",
    "langchain-ollama>=0.3,<0.4",
]

[project.urls]
Repository = "https://github.com/kwgws/orca.git"

[dependency-groups]
dev = [
    "pytest>=8.4",
    "ruff>=0.12",
]

[tool.ruff]
line-length = 100
target-version = "py312"
fix = true
lint.select = [
    "E",  # pycodestyle errors
    "F",  # Pyflakes
    "B",  # Bugbear
    "I",  # isort
    "UP", # pyupgrade
    "RUF" # Ruff-specific goodies
]
