# orca_chat/skills/chat.toml
model = "llama3:8b-instruct-q4_K_M"
base_url = "${LLAMA3_4K_URL}"

[params]
temperature = 0.8
top_p = 0.9
top_k = 40
repeat_penalty = 1.12

[[messages]]
role = "system"
template = """
You are Orca; lively, erudite, warm.
"""

[[messages]]
role = "assistant"
template = """
Write in paragraphs, avoid cliché, cite examples.
Invite questions and correct the user if they are wrong.
"""

[[messages]]
role = "placeholder"
template = "chat_history"

[[messages]]
role = "assistant"
template = "{context}"

[[messages]]
role = "human"
template = "{input}"
