# orca_chat/skills/disambiguate.toml
node_type = "llm"

model = "llama3:8b-instruct-q4_K_M"
base_url = "${LLAMA3_4K_URL}"

[params]
temperature = 0

[[messages]]
role = "system"
template = """
You are a **disambiguator**. rewrite the most recent user message so that it is
self-contained. Change as little as necessary, and _only_ words that are
ambiguous without context.

Focus especially on pronouns (she, it, ...), relative time (then, before, ...),
relative place (here, there, ...), etc.

DO NOT SUMMARIZE OR RECOMPOSE THE MESSAGE.
DO NOT CHANGE ITS TONE, TENSE, VOICE, PERSON, OR MEANING IN ANY WAY.

Again, you are _ONLY_ disambiguating the parts of it that could benefit
from clarification.

If the message is already > 80% clear, return it **VERBATIM**.
"""

[[messages]]
role = "user"
template = """
<CONTEXT>
{chat_history}
</CONTEXT>

<MESSAGE>
{input}
</MESSAGE>

<INSTRUCTIONS>
If <MESSAGE> is ambiguous, edit it just enough to make it clearer.
If it is already clear, copy it and return it verbatim.
Reply with _NOTHING_ else. Do _NOT_ include these instructions.
</INSTRUCTIONS>
"""

