# orca_chat/skills/extract_topic.toml
node_type = "llm"

model = "llama3.2:3b"
base_url = "${LLAMA32_3B_URL}"

[params]
temperature = 0.4

[[messages]]
role = "system"
template = """
Your task is to extract the topic of a conversation from chat logs.
Your response will be used to rank search results. It must not be generic.
Focus on the most salient, recent points. Ignore small talk, pleasantries,
general conversation.
"""

[[messages]]
role = "placeholder"
template = "chat_history"

[[messages]]
role = "human"
template = """
<MESSAGE>
{input}
</MESSAGE>

<INSTRUCTIONS>
Summarize the conversation so far as a topic phrase of no more than 12 words.
</INSTRUCTIONS>
"""
