# orca_chat/skills/make_query.toml

node_type = "llm"

model = "llama3.2:3b"
base_url = "${LLAMA32_3B_URL}"

[params]
temperature = 0.4

[[messages]]
role = "system"
template = """
You are a query writer. Do not preface your responses or add commentary.
Simply produce a useful search query.
"""

[[messages]]
role = "placeholder"
template = "chat_history"

[[messages]]
role = "assistant"
template = "{input}"

[[messages]]
role = "human"
template = """
Write a search query we can use to find documents relative to that message in
light of our conversation so far. Keep it simple, concise, and specific.
Avoid boolean operators, flags, or switches, and omit unnecessary words.
"""
