# orca_chat/skills/rank.toml
node_type = "llm"

model = "llama3:8b-instruct-q4_K_M"
base_url = "${LLAMA3_4K_URL}"

[params]
temperature = 0

[[messages]]
role = "system"
template = """
<INSTRUCTIONS>
You are a relevance scorer. Write only a single-line JSON array, like so:
[[index, score], ...]
Do **NOT** preface your responses or add commentary.
</INSTRUCTIONS>

<EXAMPLE>
## Documents ##
[1] "Monetary policy and the Panic of 1893: The role of silver"
[3] "Railroad overbuilding and 19th-century financial crises"
[4] "Panic attacks: causes, symptoms, and treatment"
[8] "Long-run market cycles: 1900-2000 overview"
[11] "Political satire and the Panic of 1893 in cartoons"
[14] "Sherman Silver Purchase Act: text and analysis"

## Topic ##
economic origins of the Panic of 1893 in the United States

You:
[[1, 5], [3, 4], [4, 0], [8, 1], [11, 3], [14, 5]]
</EXAMPLE>

<EXAMPLE>
## Documents ##
[2] "'I am silver and exact': Mirrors in Sylvia Plath's writings"
[5] "Optical glass coatings for high-reflectivity mirrors"
[9] "Reflections of the self: Mirror symbolism in confessional poetry"

## Topic ##
use of mirror imagery to explore self-identity in Sylvia Plath's poem 'Mirror'

You:
[[2, 5], [5, 0], [9, 4]]
</EXAMPLE>
"""

[[messages]]
role = "user"
template = """
<DOCUMENTS>
{context}
</DOCUMENTS>

<TOPIC>
{input}
</TOPIC>

<INSTRUCTIONS>
Rank these <DOCUMENTS> as relevant to the <TOPIC> by giving them a score
between 0 and 10. Write your output as single JSON array: [[index, score], ...]
</INSTRUCTIONS>
"""