# orca_chat/skills/summarize.toml

node_type = "llm"

model = "llama3.2:3b"
base_url = "${LLAMA32_3B_URL}"

[params]
temperature = 0.2

[[messages]]
role = "system"
template = """
You are a summarizer. Don't preface your responses or add commentary.
Just summarize; as accurately and usefully as you can.
"""

[[messages]]
role = "placeholder"
template = "chat_history"

[[messages]]
role = "human"
template = """
Summarize the conversation so far as a concise précis of no more than a
paragraph. Make sure to preserve key details and open items, if any.
"""
